### ISSUE TITLE
Can your reduce log4net depency?

### ISSUE THREAD

**Issue by obabac** [hancengiz/rabbitmq.log4net.gelf.appender#8]
There is currently log4net 1.2.11 marked as lowest requirement in NuGet. This is troublesome for me since I'm working on a large project and we can't afford to upgrade log4net. We're using log4net 1.2.10.

I've checked out this project and compiled it myself. So far it seems to work fine with the lowest log4net version available in NuGet. It would be great if you could lower the log4net version requirement.

**Comment by hancengiz** [comment]
Please send a pull request. I will merge and publish. Sorry for late response.
